### ISSUE TITLE
caddy-automatic-https module using storage account name for the share name when using caddy_persistence_storage_account variable

### ISSUE THREAD

**Issue by JWilkinsonMB** [getindata/terraform-azurerm-atlantis#17]
When using the caddy_persistence_storage_account variable to pass existing storage details to the module, the local for share_name is taking the storage account name (var.caddy_persistence_storage_account.**name**) instead of the share name (var.caddy_persistence_storage_account.**share_name**)

To workaround the issue you have to create a share name the same as the account name

Fix submitted in PR #16

**Comment by jakubigla** [comment]
Thanks @JWilkinsonMB - this has been merged already
